### ISSUE TITLE
Fehler bei Import in UML-Editor

### ISSUE THREAD

**Issue by oesterli** [oesterli/dmAssets#4]
Wenn ich versuche das `DM_Asset_210630.ili` in den UML-editor zu importieren (Werkzeuge> Importieren) erhalte ich nachfolgenden Fehler. ili2c läuft aber ohne Probleme (`...compiler run done ...`)durch.

```java.lang.ClassCastException: ch.ehi.interlis.domainsandconstants.UnknownType cannot be cast to ch.ehi.interlis.domainsandconstants.basetypes.BaseType
	at ch.ehi.umleditor.interlis.iliimport.TransferFromIli2cMetamodel.visitType(TransferFromIli2cMetamodel.java:1128)
	at ch.ehi.umleditor.interlis.iliimport.TransferFromIli2cMetamodel.visitAttribute(TransferFromIli2cMetamodel.java:654)
	at ch.ehi.umleditor.interlis.iliimport.TransferFromIli2cMetamodel.visitElements(TransferFromIli2cMetamodel.java:1376)
	at ch.ehi.umleditor.interlis.iliimport.TransferFromIli2cMetamodel.visitClassDef(TransferFromIli2cMetamodel.java:284)
	at ch.ehi.umleditor.interlis.iliimport.TransferFromIli2cMetamodel.visitElements(TransferFromIli2cMetamodel.java:1362)
	at ch.ehi.umleditor.interlis.iliimport.TransferFromIli2cMetamodel.visitTopicDef(TransferFromIli2cMetamodel.java:238)
	at ch.ehi.umleditor.interlis.iliimport.TransferFromIli2cMetamodel.visitElements(TransferFromIli2cMetamodel.java:1347)
	at ch.ehi.umleditor.interlis.iliimport.TransferFromIli2cMetamodel.visitModel(TransferFromIli2cMetamodel.java:919)
	at ch.ehi.umleditor.interlis.iliimport.TransferFromIli2cMetamodel.visitElements(TransferFromIli2cMetamodel.java:1318)
	at ch.ehi.umleditor.interlis.iliimport.TransferFromIli2cMetamodel.visitTransferDescription(TransferFromIli2cMetamodel.java:1443)
	at ch.ehi.umleditor.interlis.iliimport.ImportInterlis.readIliFile(ImportInterlis.java:80)
	at ch.ehi.umleditor.interlis.iliimport.ImportInterlis.doImport(ImportInterlis.java:168)
	at ch.ehi.umleditor.application.LauncherView.mniInterlisImport(LauncherView.java:3463)
	at ch.ehi.umleditor.application.LauncherView.connEtoC14(LauncherView.java:579)
	at ch.ehi.umleditor.application.LauncherView.access$2100(LauncherView.java:56)
	at ch.ehi.umleditor.application.LauncherView$IvjEventHandler.actionPerformed(LauncherView.java:182)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by signedav** [comment]
Opened an issue on umleditor repo: https://github.com/claeis/umleditor/issues/51

**Comment by oesterli** [comment]
Nach korrekter Deklaration der OID konnte das ili problemlos in den UML/INTERLIS-Editor importiert werden

**Comment by oesterli** [comment]
resolved
